build: 
	gcc matMultp.c -o matMultp
	
testX:
	echo "*************test1*************"
	./matMultp ./test1/a ./test1/b ./test1/test1_c

testY:
	echo "*************test2*************"
	./matMultp ./test2/a ./test2/b ./test2/test2_c

testZ:
	echo "*************test3*************"
	./matMultp ./test3/a ./test3/b ./test3/test3_c

test: build testX testY testZ


